// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storytime.Core;

#nullable disable

namespace Storytime.Core.Migrations
{
    [DbContext(typeof(StorytimeDbContext))]
    partial class StorytimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedItemId")
                        .HasColumnType("int");

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedItemId");

                    b.HasIndex("RelationTypeId");

                    b.HasIndex("ItemId", "RelationTypeId", "RelatedItemId")
                        .IsUnique()
                        .HasFilter("[RelatedItemId] IS NOT NULL");

                    b.ToTable("ItemRelations", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Relation")
                        .IsUnique();

                    b.ToTable("ItemRelationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Parent → child (Project contains Story, Story contains Scene, etc.)",
                            Relation = "Contains"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Any item → global rule from the project bible",
                            Relation = "UsesRule"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Scene/Beat features a character",
                            Relation = "FeaturesCharacter"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Scene/Beat location reference",
                            Relation = "TakesPlaceAt"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Any item → tone reference",
                            Relation = "UsesTone"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Scene → CallSheet (Director's interpretation of curated beats)",
                            Relation = "DirectedAs"
                        },
                        new
                        {
                            Id = 9,
                            Description = "CallSheet → Performance, or Performance → Deliverable",
                            Relation = "Produces"
                        },
                        new
                        {
                            Id = 10,
                            Description = "CallSheet → Character (Rank on the relation defines cast order)",
                            Relation = "HasRole"
                        },
                        new
                        {
                            Id = 11,
                            Description = "CallSheet → Narration (Defines the narration for a scene, with rank defining order if multiple)",
                            Relation = "Narrates"
                        });
                });

            modelBuilder.Entity("KB.Core.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Top-level story container (e.g. The Lost Drifter)",
                            Name = "Project"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A full narrative arc inside a Project",
                            Name = "Story"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Self-contained chunk with a clear goal",
                            Name = "Scene"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Single moment inside a Scene (Setup/Choice/Escalation/Climax/ResolutionHook)",
                            Name = "Beat"
                        },
                        new
                        {
                            Id = 5,
                            Description = "NPC or main traveler",
                            Name = "Character"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Scene location",
                            Name = "Location"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Project bible rule",
                            Name = "Rule"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Project bible tone/mood reference",
                            Name = "Tone"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Director's ordered cast sequence for a Scene",
                            Name = "CallSheet"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Executed result of a CallSheet by character agents",
                            Name = "Performance"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Final rendered output — prose, podcast, video, etc.",
                            Name = "Deliverable"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Narration item for call sheets",
                            Name = "Narration"
                        });
                });

            modelBuilder.Entity("Storytime.Core.Entities.AgentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ContextItemId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Established")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolCallsSummary")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentName");

                    b.HasIndex("ContextItemId");

                    b.HasIndex("Established");

                    b.HasIndex("Success");

                    b.ToTable("AgentLogs", (string)null);
                });

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.HasOne("KB.Core.Entities.ItemType", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelation", b =>
                {
                    b.HasOne("KB.Core.Entities.Item", "Item")
                        .WithMany("Relations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KB.Core.Entities.Item", "RelatedItem")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("RelatedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KB.Core.Entities.ItemRelationType", "RelationType")
                        .WithMany("ItemRelations")
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedItem");

                    b.Navigation("RelationType");
                });

            modelBuilder.Entity("KB.Core.Entities.Item", b =>
                {
                    b.Navigation("IncomingRelations");

                    b.Navigation("Relations");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemRelationType", b =>
                {
                    b.Navigation("ItemRelations");
                });

            modelBuilder.Entity("KB.Core.Entities.ItemType", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
